FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV MODEL_PATH=models/champion

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src src
COPY api api
COPY params.yaml params.yaml
COPY models/champion models/champion

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
